#Try to include a vcpkg toolchain file if none was defined and VCPKG_ROOT is defined
if (DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
	set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "" FORCE)
endif()
if (NOT DEFINED ED_CXX)
    set(ED_CXX 20 CACHE STRING "C++ standard number (14, 17, 20)")
    if (${ED_CXX} LESS 14)
        message(FATAL_ERROR "C++${ED_CXX} standard is out of support")
    endif()
    if ("${PROJECT_NAME}" STREQUAL "")
        message(STATUS "C++${ED_CXX} is set by edge")
    else()
        message(STATUS "C++${ED_CXX} is set by ${PROJECT_NAME}")
    endif()
else()
    if ("${PROJECT_NAME}" STREQUAL "")
        message(STATUS "C++${ED_CXX} is used for edge")
    else()
        message(STATUS "C++${ED_CXX} is used for ${PROJECT_NAME}")
    endif()
endif()
add_compile_definitions(ED_CXX=${ED_CXX})