#ifndef VI_INTERNAL_TYPES_HPP
#define VI_INTERNAL_TYPES_HPP
#define EXCEPTIONCAT_STANDARD "standard_error"
#define EXCEPTIONCAT_SYSTEM "system_error"
#define EXCEPTIONCAT_GENERIC "generic_error"
#define EXCEPTIONCAT_VM "vm_error"
#define EXCEPTIONCAT_RANGE "range_error"
#define EXCEPTIONCAT_ALLOCATION "allocation_error"
#define EXCEPTIONCAT_TEMPLATE "template_error"
#define EXCEPTIONCAT_TYPE "type_error"
#define EXCEPTIONCAT_ASYNC "async_error"
#define EXCEPTIONCAT_SYNC "sync_error"
#define EXCEPTION_OUTOFBOUNDS EXCEPTIONCAT_RANGE, "index is outside of range"
#define EXCEPTION_OUTOFMEMORY EXCEPTIONCAT_ALLOCATION, "out of available memory"
#define EXCEPTION_TOOLARGESIZE EXCEPTIONCAT_ALLOCATION, "too much memory has been requested"
#define EXCEPTION_TEMPLATEMISMATCH EXCEPTIONCAT_TEMPLATE, "template type does not match the type that was passed to an object"
#define EXCEPTION_TEMPLATEMULTIPLECOMPARATORS EXCEPTIONCAT_TEMPLATE, "template type has multiple opCmp implementations"
#define EXCEPTION_TEMPLATENOCOMPARATORS EXCEPTIONCAT_TEMPLATE, "template type has no opCmp implementation"
#define EXCEPTION_TEMPLATEMULTIPLEEQCOMPARATORS EXCEPTIONCAT_TEMPLATE, "template type has multiple opEquals and/or opCmp implementations"
#define EXCEPTION_TEMPLATENOEQCOMPARATORS EXCEPTIONCAT_TEMPLATE, "template type has no opEquals or opCmp implementation"
#define EXCEPTION_COPYFAIL EXCEPTIONCAT_TYPE, "cannot copy this type of object"
#define EXCEPTION_NULLPOINTER EXCEPTIONCAT_TYPE, "trying to access a null pointer instance"
#define EXCEPTION_ACCESSINVALID EXCEPTIONCAT_TYPE, "accessing non-existing value"
#define EXCEPTION_INVALIDINITIATOR EXCEPTIONCAT_TYPE, "type must be a handle or null"
#define EXCEPTION_PROMISEREADY EXCEPTIONCAT_ASYNC, "trying to settle a promise that is already fulfilled"
#define EXCEPTION_PROMISENOTREADY EXCEPTIONCAT_ASYNC, "trying to unwrap a promise that is not fulfilled"
#define EXCEPTION_MUTEXNOTOWNED EXCEPTIONCAT_SYNC, "trying to unlock a mutex that is not owned by this thread"
#define TYPENAME_ARRAY "array"
#define TYPENAME_STRING "string"
#define TYPENAME_DICTIONARY "dictionary"
#define TYPENAME_ANY "any"
#define TYPENAME_CLOSURE "closure"
#define TYPENAME_THREAD "thread"
#define TYPENAME_PROMISE "promise"
#define TYPENAME_SCHEMA "schema"
#define TYPENAME_DECIMAL "decimal"
#define TYPENAME_VARIANT "variant"
#define TYPENAME_FILELINK "file_link"
#define TYPENAME_REGEXMATCH "regex_match"
#define TYPENAME_REGEXSOURCE "regex_source"
#define TYPENAME_SOCKETCERTIFICATE "socket_certificate"
#define TYPENAME_ASSETFILE "asset_file"
#define TYPENAME_LDBCHECKPOINT "ldb::checkpoint"
#define TYPENAME_HTTPERRORFILE "http::error_file"
#define TYPENAME_HTTPMIMETYPE "http::mime_type"
#define TYPENAME_HTTPRESOURCEINFO "http::resource_info"
#define TYPENAME_HTTPSERVER "http::server"
#define TYPENAME_SMTPRECIPIENT "smtp::recipient"
#define TYPENAME_SMTPATTACHMENT "smtp::attachment"
#endif